openapi: 3.0.3
info:
  title: CODING SOON - TOREOLRE API
  description: CODING SOON의 API DOCUMENT.
  version: '1.0.0'
servers:
  - url: http://localhost:5001
tags:
  - name: test
    description: test
path:
  /:
  get:
    description: main page
    responses:
      '200':
        description: main string
        content:
          application/json:
            schema:
              type: string
              items:
                $ref: '#/components/schemas/pet'
