openapi: 3.0.0
info:
    description: 엘리스 AI 트랙 2차 데이터 프로젝트 팀 CODING SOON의 API DOCUMENT.
    version: "1.0.0"
    title: CODING SOON - TOREOLRE API
    termsOfService: "http://swagger.io/terms/"
    license:
        name: MIT
servers:
    - description: dev server
      url: http://localhost:5001
tags:
    - name: user
      description: 유저관리 API
    - name: product
      description: 상품 API
    - name: order
      description: 주문/결제 API
    - name: cart
      description: 장바구니 API
    - name: bookmark
      description: 북마크 API
path:
    $ref: "./paths/index.yaml"
